package part

const Account = "account"
const Action = "action"
const Actions = "actions"
const Bindings = "bindings"
const Cast = "cast"
const Entity = "entity"
const Dialog = "dialog"
const Imaging = "imaging"
const Itembag = "itembag"
const Item = "item"
const Itemslot = "itemslot"
const Itemslots = "itemslots"
const Menu = "menu"
const Menus = "menus"
const Movement = "movement"
const Player = "player"
const Pokemon = "pokemon"
const Session = "session"
const Stats = "stats"
const Terrain = "terrain"
const Universe = "universe"
const Walk = "walk"
